title: <a class="page-title" href="/forthel-syntax/">The syntax of ForTheL</a>
description: <span></span> # To hide the description
baseurl: "/forthel-syntax"
url: "https://mcearl.github.io"
github_username:  McEarl
remote_theme: pages-themes/cayman
show_downloads: false
github:
  is_project_page: false # To hide "View on GitHub" button

# Build settings
plugins:
  - jekyll-feed
